/* Hearing 360 Degree — shared scripts */
const WA_NUMBER = "918583927070"; // clinic WhatsApp

/* Mobile nav */
const toggle = document.querySelector(".nav-toggle");
const nav = document.querySelector(".nav");
if (toggle) {
  toggle.addEventListener("click", () => {
    nav.classList.toggle("open");
    toggle.classList.toggle("open");
    toggle.setAttribute("aria-expanded", nav.classList.contains("open"));
  });
  nav.querySelectorAll("a").forEach(a => a.addEventListener("click", () => {
    nav.classList.remove("open"); toggle.classList.remove("open");
  }));
}

/* Scroll reveal */
const io = new IntersectionObserver(es => es.forEach(e => {
  if (e.isIntersecting) { e.target.classList.add("in"); io.unobserve(e.target); }
}), { threshold: .12 });
document.querySelectorAll(".reveal").forEach(el => io.observe(el));

/* ---------------- Inquiry modal ---------------- */
const modal = document.getElementById("inquiryModal");
function openInquiry(product) {
  if (!modal) return;
  document.getElementById("inqProduct").value = product || "General inquiry";
  document.getElementById("inqTitle").textContent = product ? "Inquire: " + product : "Drop an Inquiry";
  modal.classList.add("open");
  document.body.style.overflow = "hidden";
}
function closeInquiry() {
  modal.classList.remove("open");
  document.body.style.overflow = "";
}
if (modal) {
  modal.addEventListener("click", e => { if (e.target === modal) closeInquiry(); });
  document.querySelector(".modal-close").addEventListener("click", closeInquiry);
  document.getElementById("inquiryForm").addEventListener("submit", e => {
    e.preventDefault();
    const f = e.target;
    const msg =
      "New Inquiry — Hearing 360 Degree website%0A" +
      "Product/Service: " + encodeURIComponent(f.product.value) + "%0A" +
      "Name: " + encodeURIComponent(f.name.value) + "%0A" +
      "Phone: " + encodeURIComponent(f.phone.value) + "%0A" +
      "Message: " + encodeURIComponent(f.message.value);
    window.open("https://wa.me/" + WA_NUMBER + "?text=" + msg, "_blank");
    closeInquiry();
    f.reset();
  });
}
document.addEventListener("click", e => {
  const btn = e.target.closest("[data-inquiry]");
  if (btn) openInquiry(btn.getAttribute("data-inquiry"));
});

/* Download brochure (demo PDF-style text spec sheet) */
document.addEventListener("click", e => {
  const btn = e.target.closest("[data-download]");
  if (!btn) return;
  const name = btn.getAttribute("data-download");
  const content =
`HEARING 360 DEGREE — PRODUCT SPECIFICATION (SAMPLE)
====================================================
Product : ${name}
Clinic  : Hearing 360 Degree, 133 Kanungo Park, Garia, Kolkata - 700084
Phone   : 85839 27070 / 74392 97070
Email   : 360degreehearing@gmail.com

This is a sample brochure generated by the design prototype.
Final brochures (PDF) will be attached per product after client approval.`;
  const blob = new Blob([content], { type: "text/plain" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = name.replace(/\s+/g, "-") + "-brochure.txt";
  a.click();
  URL.revokeObjectURL(a.href);
});

/* ---------------- Product filtering ---------------- */
const grid = document.getElementById("productGrid");
if (grid) {
  const selCompany = document.getElementById("fCompany");
  const selType = document.getElementById("fType");
  const selTech = document.getElementById("fTech");
  const search = document.getElementById("fSearch");
  const noRes = document.getElementById("noResults");
  const count = document.getElementById("resultCount");

  function applyFilters() {
    let shown = 0;
    grid.querySelectorAll(".product-card").forEach(card => {
      const okCompany = !selCompany.value || card.dataset.company === selCompany.value;
      const okType = !selType.value || card.dataset.type === selType.value;
      const okTech = !selTech.value || card.dataset.tech.includes(selTech.value);
      const okSearch = !search.value || card.textContent.toLowerCase().includes(search.value.toLowerCase());
      const show = okCompany && okType && okTech && okSearch;
      card.style.display = show ? "" : "none";
      if (show) shown++;
    });
    noRes.style.display = shown ? "none" : "block";
    count.textContent = shown + " product" + (shown === 1 ? "" : "s");
  }
  [selCompany, selType, selTech].forEach(s => s.addEventListener("change", applyFilters));
  search.addEventListener("input", applyFilters);
  applyFilters();
}

/* ---------------- Contact form ---------------- */
const contactForm = document.getElementById("contactForm");
if (contactForm) {
  contactForm.addEventListener("submit", e => {
    e.preventDefault();
    const f = e.target;
    const msg =
      "Contact form — Hearing 360 Degree website%0A" +
      "Name: " + encodeURIComponent(f.name.value) + "%0A" +
      "Phone: " + encodeURIComponent(f.phone.value) + "%0A" +
      "Email: " + encodeURIComponent(f.email.value) + "%0A" +
      "Address: " + encodeURIComponent(f.address.value) + "%0A" +
      "Message: " + encodeURIComponent(f.message.value);
    window.open("https://wa.me/" + WA_NUMBER + "?text=" + msg, "_blank");
    f.reset();
    const ok = document.getElementById("formOk");
    if (ok) { ok.style.display = "block"; setTimeout(() => ok.style.display = "none", 6000); }
  });
}

/* ---------------- Auto lead-capture popup (Special Offer) ---------------- */
(function () {
  const pop = document.getElementById("offerPopup");
  if (!pop) return;
  // Fix pointer events on burst element
  const burst = pop.querySelector(".burst");
  if (burst) burst.style.pointerEvents = "none";
  let seen = false;
  let footerPromptDone = false;
  try { seen = sessionStorage.getItem("h360_offer_seen") === "1"; } catch (e) {}
  try { footerPromptDone = sessionStorage.getItem("h360_offer_footer_seen") === "1"; } catch (e) {}
  function showPop(force) {
    if (document.querySelector(".modal.open")) return;
    if (!force && seen) return;
    pop.classList.add("open");
    document.body.style.overflow = "hidden";
    seen = true;
    try { sessionStorage.setItem("h360_offer_seen", "1"); } catch (e) {}
  }
  function hidePop() {
    pop.classList.remove("open");
    document.body.style.overflow = "";
  }
  setTimeout(() => showPop(false), 5000); // auto-open after 5s on first visit
  // exit-intent (desktop)
  document.addEventListener("mouseout", e => {
    if (!e.relatedTarget && e.clientY <= 0) showPop(false);
  });
  // Last-chance prompt: user has scrolled all the way to the footer (works on mobile too,
  // where exit-intent can't fire) — show again even if already seen/dismissed once.
  const footerEl = document.querySelector(".footer");
  if (footerEl) {
    const footerIO = new IntersectionObserver(entries => {
      entries.forEach(entry => {
        if (entry.isIntersecting && !footerPromptDone) {
          footerPromptDone = true;
          try { sessionStorage.setItem("h360_offer_footer_seen", "1"); } catch (e) {}
          showPop(true);
          footerIO.unobserve(footerEl);
        }
      });
    }, { threshold: .15 });
    footerIO.observe(footerEl);
  }
  pop.addEventListener("click", e => { if (e.target === pop) hidePop(); });
  pop.querySelector(".modal-close").addEventListener("click", hidePop);
  document.querySelectorAll("[data-open-offer]").forEach(b => b.addEventListener("click", () => showPop(true)));
  document.getElementById("offerForm").addEventListener("submit", e => {
    e.preventDefault();
    const f = e.target;
    const msg =
      "SPECIAL OFFER claim — Hearing 360 Degree website%0A" +
      "Offer: FREE Hearing Test + FREE Hearing Aid Trial%0A" +
      "Name: " + encodeURIComponent(f.name.value) + "%0A" +
      "Phone: " + encodeURIComponent(f.phone.value);
    window.open("https://wa.me/" + WA_NUMBER + "?text=" + msg, "_blank");
    hidePop();
    f.reset();
  });
})();

/* ---------------- Company pre-filter from menu (?company=Signia) ---------------- */
(function () {
  const sel = document.getElementById("fCompany");
  if (!sel) return;
  const co = new URLSearchParams(location.search).get("company");
  if (co) { sel.value = co; sel.dispatchEvent(new Event("change")); }
})();

/* ---------------- Highlights slider ---------------- */
(function () {
  const track = document.getElementById("hlTrack");
  const dotsWrap = document.getElementById("hlDots");
  if (!track || !dotsWrap) return;
  const cards = Array.from(track.children);
  const prevBtn = document.querySelector(".hl-prev");
  const nextBtn = document.querySelector(".hl-next");
  let index = 0;

  cards.forEach((_, i) => {
    const dot = document.createElement("button");
    dot.setAttribute("aria-label", "Go to highlight " + (i + 1));
    if (i === 0) dot.classList.add("active");
    dot.addEventListener("click", () => goTo(i));
    dotsWrap.appendChild(dot);
  });
  const dots = Array.from(dotsWrap.children);

  function goTo(i) {
    index = (i + cards.length) % cards.length;
    track.scrollTo({ left: cards[index].offsetLeft, behavior: "smooth" });
    dots.forEach((d, di) => d.classList.toggle("active", di === index));
  }
  if (prevBtn) prevBtn.addEventListener("click", () => goTo(index - 1));
  if (nextBtn) nextBtn.addEventListener("click", () => goTo(index + 1));

  let timer = setInterval(() => goTo(index + 1), 4500);
  function pause() { clearInterval(timer); }
  function resume() { timer = setInterval(() => goTo(index + 1), 4500); }
  track.addEventListener("mouseenter", pause);
  track.addEventListener("mouseleave", resume);
  track.addEventListener("touchstart", pause, { passive: true });
  track.addEventListener("touchend", resume);

  let scrollTimeout;
  track.addEventListener("scroll", () => {
    clearTimeout(scrollTimeout);
    scrollTimeout = setTimeout(() => {
      let closest = 0, min = Infinity;
      cards.forEach((c, i) => {
        const d = Math.abs(c.offsetLeft - track.scrollLeft);
        if (d < min) { min = d; closest = i; }
      });
      index = closest;
      dots.forEach((d, di) => d.classList.toggle("active", di === index));
    }, 100);
  });
})();

/* ---------------- Mobile CTA: stays visible throughout scroll for lead capture,
   only steps aside while a modal/popup is open on top of it ---------------- */
(function () {
  const bar = document.querySelector(".mobile-cta");
  if (!bar) return;
  function sync() {
    bar.classList.toggle("hidden", !!document.querySelector(".modal.open"));
  }
  new MutationObserver(sync).observe(document.body, { attributes: true, attributeFilter: ["class"], subtree: true });
  sync();
})();
